Basic: QBasic fixes/enabling. Recursive includes.
Enable QBasic console mode usage and fix bugs in newline handling
differences with C64 basic (cbm). To enable console mode for QBasic
programs, have basicpp.py prefix the output with the QB64 specific
console activation variables/functions.

One change to basicpp.py to make this change more straightfowards is
recursive includes so that includes can appear in more than just the
top level step files. This allows us to conditionally include the
right readline implementation. For QBasic in the special console mode
(instead of the default full-screen UI mode) we need to use the LINE
INPUT command in order to read input.

diff --git a/basic/run b/basic/run
--- a/basic/run
+++ b/basic/run
@@ -1,4 +1,8 @@
 #!/bin/bash
 cd $(dirname $0)
 (echo "(list $(for a in "${@}"; do echo -n "\"${a}\""; done))") > .args.mal
-exec cbmbasic ${STEP:-stepA_mal}.bas "${@}"
+case ${basic_MODE:-cbm} in
+    cbm)    exec cbmbasic ${STEP:-stepA_mal}.bas "${@}" ;;
+    qbasic) exec ./${STEP:-stepA_mal} "${@}" ;;
+    *)      echo "Invalid basic_MODE: ${basic_MODE}"; exit 2 ;;
+esac
